// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgdorfbxdagutzsyfpgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnZG9yZmJ4ZGFndXR6c3lmcGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTAzMTYsImV4cCI6MjA2ODMyNjMxNn0.UpYoV8kHiuth1s_dVE7c7_ZxEBQMeykGzpdwszcNPQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});